import 'package:academic_project/domain/ai_response.dart';
import 'package:academic_project/presentation/ai/provider/ai_provider.dart';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:flutter_animate/flutter_animate.dart';

class AiAssistantScreen extends ConsumerStatefulWidget {
  final int? noteId;
  const AiAssistantScreen({super.key, this.noteId});

  @override
  ConsumerState<AiAssistantScreen> createState() => _AiAssistantScreenState();
}

class _AiAssistantScreenState extends ConsumerState<AiAssistantScreen> {
  final TextEditingController _controller = TextEditingController();

  Future<void> _generateAndSavePdf(AiResponse response, String topic) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Text(
                'EduVision AI Assistant - $topic',
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Header(level: 1, text: 'Academic Definition'),
            pw.Paragraph(text: response.academicDefinition),
            pw.Header(level: 1, text: 'Simple Definition'),
            pw.Paragraph(text: response.simpleDefinition),
            pw.Header(level: 1, text: 'Exam Standard Description'),
            pw.Paragraph(text: response.examStandardDescription),
            pw.Footer(
              margin: const pw.EdgeInsets.only(top: 20),
              trailing: pw.Text(
                'Generated by EduVision AI',
                style: const pw.TextStyle(color: PdfColors.grey),
              ),
            ),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }

  void _copyToClipboard(String text) {
    Clipboard.setData(ClipboardData(text: text));
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(const SnackBar(content: Text('Copied to clipboard!')));
  }

  @override
  Widget build(BuildContext context) {
    final aiState = ref.watch(aiProvider);

    return Scaffold(
      backgroundColor: const Color(0xFF0F172A),
      appBar: AppBar(
        title: Text(
          'EduVision AI Assistant',
          style: GoogleFonts.outfit(fontWeight: FontWeight.bold),
        ),
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            _buildSearchInput(),
            const SizedBox(height: 24),
            Expanded(
              child: aiState.isLoading
                  ? const Center(
                      child: CircularProgressIndicator(
                        color: Colors.blueAccent,
                      ),
                    )
                  : aiState.response != null
                  ? _buildAiResponseView(aiState.response!)
                  : _buildEmptyState(),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSearchInput() {
    return Container(
      decoration: BoxDecoration(
        color: const Color(0xFF1E293B),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.blueAccent.withOpacity(0.3)),
      ),
      child: TextField(
        controller: _controller,
        style: const TextStyle(color: Colors.white),
        decoration: InputDecoration(
          hintText: 'Ask about any concept...',
          hintStyle: TextStyle(color: Colors.white.withOpacity(0.5)),
          prefixIcon: const Icon(Icons.psychology, color: Colors.blueAccent),
          suffixIcon: IconButton(
            icon: const Icon(Icons.send, color: Colors.blueAccent),
            onPressed: () {
              if (_controller.text.isNotEmpty) {
                ref.read(aiProvider.notifier).askAi(_controller.text);
              }
            },
          ),
          border: InputBorder.none,
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 20,
            vertical: 15,
          ),
        ),
        onSubmitted: (value) {
          if (value.isNotEmpty) {
            ref.read(aiProvider.notifier).askAi(value);
          }
        },
      ),
    );
  }

  Widget _buildAiResponseView(AiResponse response) {
    return SingleChildScrollView(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildResponseCard(
            'Academic Definition',
            response.academicDefinition,
            Icons.menu_book,
          ),
          _buildResponseCard(
            'Simple Definition',
            response.simpleDefinition,
            Icons.lightbulb,
          ),
          _buildResponseCard(
            'Exam Standard Description',
            response.examStandardDescription,
            Icons.assignment,
          ),
          const SizedBox(height: 20),
          Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              _buildActionButton(
                icon: Icons.copy,
                label: 'Copy All',
                onPressed: () {
                  final text =
                      "Academic Definition: ${response.academicDefinition}\n\n"
                      "Simple Definition: ${response.simpleDefinition}\n\n"
                      "Exam Standard Description: ${response.examStandardDescription}";
                  _copyToClipboard(text);
                },
              ),
              const SizedBox(width: 12),
              _buildActionButton(
                icon: Icons.picture_as_pdf,
                label: 'Extract PDF',
                onPressed: () =>
                    _generateAndSavePdf(response, _controller.text),
              ),
              if (widget.noteId != null) ...[
                const SizedBox(width: 12),
                _buildActionButton(
                  icon: Icons.attachment,
                  label: 'Attach to Note',
                  onPressed: () => _attachToNote(response, _controller.text),
                ),
              ],
            ],
          ).animate().fadeIn(delay: 500.ms),
        ],
      ),
    );
  }

  Future<void> _attachToNote(AiResponse response, String topic) async {
    try {
      final pdf = pw.Document();
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return [
              pw.Header(level: 0, text: 'EduVision AI Assistant - $topic'),
              pw.Header(level: 1, text: 'Academic Definition'),
              pw.Paragraph(text: response.academicDefinition),
              pw.Header(level: 1, text: 'Simple Definition'),
              pw.Paragraph(text: response.simpleDefinition),
              pw.Header(level: 1, text: 'Exam Standard Description'),
              pw.Paragraph(text: response.examStandardDescription),
            ];
          },
        ),
      );

      final bytes = await pdf.save();

      // We need to import the data source or use a provider
      // For simplicity, I'll use a local instance here or you can define a provider
      // Given the previous files, I'll use Dio to post it.

      final dio = Dio(
        BaseOptions(baseUrl: 'http://localhost:8080/api/resources'),
      );
      final storage = const FlutterSecureStorage();
      final token = await storage.read(key: 'jwt');

      final formData = FormData.fromMap({
        'file': MultipartFile.fromBytes(
          bytes,
          filename: '${topic.replaceAll(' ', '_')}_ai_summary.pdf',
        ),
      });

      await dio.post(
        '/upload',
        data: formData,
        queryParameters: {
          'title': '$topic (AI Summary)',
          'description': 'AI generated structured explanation for $topic',
          'type': 'PDF',
          'noteId': widget.noteId,
        },
        options: Options(headers: {'Authorization': 'Bearer $token'}),
      );

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Successfully attached to note!')),
      );
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Failed to attach: $e')));
    }
  }

  Widget _buildResponseCard(String title, String content, IconData icon) {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: const Color(0xFF1E293B),
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.2),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, color: Colors.blueAccent, size: 20),
              const SizedBox(width: 10),
              Text(
                title,
                style: GoogleFonts.outfit(
                  color: Colors.blueAccent,
                  fontWeight: FontWeight.bold,
                  fontSize: 16,
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Text(
            content,
            style: GoogleFonts.inter(
              color: Colors.white.withOpacity(0.9),
              fontSize: 15,
              height: 1.6,
            ),
          ),
        ],
      ),
    ).animate().slideY(begin: 0.1, duration: 400.ms).fadeIn();
  }

  Widget _buildActionButton({
    required IconData icon,
    required String label,
    required VoidCallback onPressed,
  }) {
    return ElevatedButton.icon(
      onPressed: onPressed,
      icon: Icon(icon, size: 18),
      label: Text(label),
      style: ElevatedButton.styleFrom(
        backgroundColor: Colors.blueAccent,
        foregroundColor: Colors.white,
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(
            Icons.auto_awesome,
            size: 80,
            color: Colors.blueAccent.withOpacity(0.2),
          ),
          const SizedBox(height: 16),
          Text(
            'What can I help you learn today?',
            style: GoogleFonts.outfit(
              color: Colors.white.withOpacity(0.5),
              fontSize: 18,
            ),
          ),
        ],
      ),
    );
  }
}
